[package]
name = "rsa-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
num-bigint = { version = "0.4.4", features = ["rand"] }
num-traits = "0.2"
serde = {version = "1.0.219", features = ["derive"]}
base64 = "0.22.1"
serde_json = "1.0.140"
